
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button btOpen;

	private global::Gtk.FileChooserWidget filechooserwidget1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btOpen = new global::Gtk.Button();
		this.btOpen.CanFocus = true;
		this.btOpen.Name = "btOpen";
		this.btOpen.UseUnderline = true;
		this.btOpen.Label = global::Mono.Unix.Catalog.GetString("Open");
		this.fixed1.Add(this.btOpen);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btOpen]));
		w1.X = 15;
		w1.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.filechooserwidget1 = new global::Gtk.FileChooserWidget(((global::Gtk.FileChooserAction)(0)));
		this.filechooserwidget1.Name = "filechooserwidget1";
		this.fixed1.Add(this.filechooserwidget1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.filechooserwidget1]));
		w2.X = 61;
		w2.Y = 16;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 310;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btOpen.Clicked += new global::System.EventHandler(this.OnBtOpenClicked);
	}
}
